### ISSUE TITLE
Decide on framework

### ISSUE THREAD

**Issue by freesig** [nannou-org/guide#1]
I'm pretty happy to use mdBook as it has:
- A well written [guide](https://rust-lang-nursery.github.io/mdBook/).
- Can run rust code in the guide (This means all examples need to actually work and won't go out of date).
- Works with Travis. So we can easily setup CI.
- Rust book uses it so we can just copy how they have things setup.
- It matches the Rust standard users might feel more comfortable using mdBook if they have used it in other Rust projects.
- It's written in Rust :grin:
- It's opensource.

Happy to take other suggestions though.
Other options I know of:
-  [Gitbook](https://www.gitbook.com/)
- Others?

It would be cool to make this decision soon though so we can get started.

**Comment by mitchmindtree** [comment]
I agree that mdbook looks like the most promising approach atm! Also lots of examples of usage e.g. the rust book, rustonomicon, glium book, etc.

**Comment by tpltnt** [comment]
`mdbook` seems to be the tool of choice by now. Can this issue be closed?

**Comment by mitchmindtree** [comment]
Yeah sounds good!

If anyone reading this feels there is a better direction we might take, feel free to open a new issue with your recommendation :)
