### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by freesig** [nannou-org/guide#2]
Need to figure out how we will host?
- Netlify
- Github pages
- Others

**Comment by mitchmindtree** [comment]
Maybe it would be nice to host this alongside the website? E.g. nannou.cc/book, or book.nannou.cc, or something along these lines?

**Comment by freesig** [comment]
Yeh I agree but I think it would be just a url that links them because they are going to be created by different generates under the hood.
So you still have independent githubs and even hosting but then just point nannou.cc/book or nannou.cc/guide at where this is hosted.

**Comment by JoshuaBatty** [comment]
Going to close this for now as we have a working solution with netlify and the guide.
