### ISSUE TITLE
missing licensing

### ISSUE THREAD

**Issue by tpltnt** [nannou-org/guide#5]
Hi there,

under which license should the book/documentation be released/distributed?

Cheers,
tpltnt

**Comment by mitchmindtree** [comment]
Good question!

My first instinct is to go with the MIT/Apache-2 license following suite with nannou and Rust itself. I think it's especially useful for readers to be able to copy-paste code directly into their own projects.

That said, maybe the writing and guide itself (everything but the code snippets) should be under a copyleft license to stop folks copying the whole thing and offering paid online courses out of it (when the user could just get it for free here), or to stop some publisher copying the entire thing and selling a non-official print version? Or maybe we don't mind about these things? What are your thoughts? Also cc @JoshuaBatty @freesig

**Comment by JoshuaBatty** [comment]
I vote for a copyleft license. This is the approach the book of shaders is taking for the exact reasons @mitchmindtree outlined above.

**Comment by tpltnt** [comment]
I would contribute things if I were able to (re-)use them later (even commercially) and not get ripped of by others.

**Comment by freesig** [comment]
I agree with copyleft

**Comment by tpltnt** [comment]
The "book of shaders" has "all rights reserved" ([source](https://github.com/patriciogonzalezvivo/thebookofshaders/blob/master/LICENSE)), which seems to be the opposite of [copyleft](https://en.wikipedia.org/wiki/Copyleft). So what are the terms going to be for this project?

**Comment by JoshuaBatty** [comment]
My bad i was just trying to remember off the top of my head. I'm happy with copyleft still.

**Comment by mitchmindtree** [comment]
One issue with the copyleft approach is that it's not clear to me how we allow for certain kinds of commercial re-use and disallow others - e.g. we don't want someone publishing a non-official, word-for-word print of the book, but we still want to allow teachers and creative coding workshops to give lessons using the guide as a basis as the value they provide is in their "guiding hand", support, ability to explain it in a different way, availability for questions etc. Plus it helps to spread the word about nannou!

I've just noticed that The Rust Programming Language official book seems to be MIT/Apache2 licensed just like the Rust src is. They've also successfully sold their own official printed version and I haven't heard any issues from them about problems related to their licensing... then again I haven't been following their repo too closely.

I'm wondering if it's easiest to just use the same licensing as for Nannou itself? I'm personally leaning this way as I am not a lawyer, and don't really know how to put something together that is more particular about commercial usage that also looks familiar enough and is simple enough that it doesn't deter future contributors.

**Comment by tpltnt** [comment]
Just as a hint: [choosealicense.com](https://choosealicense.com/non-software/)

**Comment by tpltnt** [comment]
ping
