### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by albizures** [nannou-org/guide#50]
Reading through the guide, I noticed that some links are broken.

So far just these two:
https://github.com/nannou-org/guide/blob/6d1d86379c026c4264d62f7f701fec442e1c3cd3/src/tutorials/basics/anatomy-of-a-nannou-app.md#L65-L68
https://github.com/nannou-org/guide/blob/6d1d86379c026c4264d62f7f701fec442e1c3cd3/src/tutorials/basics/anatomy-of-a-nannou-app.md#L206-L207

**Comment by mitchmindtree** [comment]
Thanks for the report!

These two links are currently broken due to a build issue on docs.rs with the latest version of nannou. This should be fixed once we get around to publishing the next version. I'll leave this issue open until then as a reference for others.

**Comment by mitchmindtree** [comment]
These should be fixed now that 0.13 is published :)
