### ISSUE TITLE
example draw getting started on macOS Catalina uses an undeclared or module

### ISSUE THREAD

**Issue by matthiasdebernardini** [nannou-org/guide#54]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/32387851/75996887-d404a600-5efe-11ea-9056-4c02834aedce.png">

`❯ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)`

error[E0433]: failed to resolve: could not find `__rt` in `quote`

I think a module is missing or possibly misspelled?

**Comment by mitchmindtree** [comment]
I just ran into this myself, then tried `cargo update` and it seems to be fixed! It looks like a dependency must have published a buggy release by mistake and fixed it soon after. Let me know if `cargo update` fixes this for you and we can consider this closed :)

**Comment by matthiasdebernardini** [comment]
Brilliant! 

It compiled no problems, runs nicely.
